listen:
  - 0.0.0.0:4873

web:
  enable: true
  title: Package Registry
  logo: ./logo.png
  primary_color: "#282c33"

storage: ./storage

auth:
  htpasswd:
    file: ./htpasswd

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  "**":
    access: $all
    publish: $all

logs:
  - { type: stdout, format: pretty, level: http }
